# Generated by Django 3.1.5 on 2021-01-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='like_posts',
            field=models.ManyToManyField(blank=True, to='record.Sentence'),
        ),
    ]
