# Generated by Django 3.1.5 on 2021-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
        ('accounts', '0003_auto_20210121_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='like_posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_users', to='record.Sentence'),
        ),
        migrations.AlterField(
            model_name='member',
            name='unlike_posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='unlike_users', to='record.Sentence'),
        ),
    ]
